### ISSUE TITLE
Comment the code

### ISSUE THREAD

**Issue by iblancasa** [retejo/retejo.me#3]
Please, add comments to the code

**Comment by vypr** [comment]
I will, eventually, once I get more of the code going. For now, if you're trying to help with creating unit tests, don't worry about 'em. The code isn't mature enough to where I need them just yet.

**Comment by iblancasa** [comment]
Yes. There is not enough code but it is difficult to create, for example, unit tests if you are not sure about what does the code

**Comment by vypr** [comment]
I wrote the code, mate. I know what the code does. :P

**Comment by iblancasa** [comment]
Yes, you. But other potential contributors...
It is your decision

**Comment by vypr** [comment]
I will be adding comments, trust me. Just give me a little bit and they'll be added in the next few pushes. :)

**Comment by vypr** [comment]
Done in f6aebcb. Thoughts?

**Comment by iblancasa** [comment]
Fantastic!

**Comment by vypr** [comment]
Glad I could help. :)
